apiVersion: v1
kind: Service
metadata:
  name: mass-static
  labels:
    app: mass-static
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: mass-static
