apiVersion: apps/v1
kind: Deployment
metadata:
  name: substrate-be
  labels:
    app: substrate-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: substrate-be
  template:
    metadata:
      labels:
        app: substrate-be
    spec:
      containers:
        - name: substrate-be
          image: "gcr.io/mass-276203/mass:dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
