apiVersion: v1
kind: Service
metadata:
  name: substrate-be
  labels:
    app: substrate-be
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
  selector:
    app: substrate-be
