apiVersion: v1
kind: Service
metadata:
  name: substrate-be
  labels:
    app: substrate-be
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 50051
    nodePort: 30037
    protocol: TCP
  selector:
    app: substrate-be
